# Generated by Django 4.1.2 on 2023-02-24 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='profile/')),
                ('contact', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('refcontact', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('country', models.CharField(choices=[('Pk', 'Pakistan'), ('O', 'Other')], max_length=3)),
                ('city', models.CharField(choices=[('P', 'Peshawar'), ('I', 'Islamabad'), ('L', 'Lahore')], max_length=3)),
                ('role', models.CharField(choices=[('AD', 'Administratore'), ('DE', 'Data Entry'), ('MD', 'Moderator')], max_length=3)),
            ],
        ),
    ]
