# Generated by Django 4.1.2 on 2023-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_detail',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client_detail',
            name='city',
            field=models.CharField(choices=[('P', 'Peshawar'), ('L', 'Lahore'), ('I', 'islamabad')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='client_detail',
            name='country',
            field=models.CharField(choices=[('pk', 'Pakistan'), ('O', 'Other')], default='', max_length=2),
        ),
    ]
