# Generated by Django 4.1.2 on 2023-02-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_add_team_member_remove_team_member_refcontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_team_member',
        ),
    ]
