# Generated by Django 4.1.2 on 2023-02-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_alter_team_member_city_alter_team_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='city',
            field=models.CharField(blank=True, choices=[('peshawar', 'Peshawar'), ('islamabad', 'Islamabad'), ('lahore', 'Lahore')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='country',
            field=models.CharField(blank=True, choices=[('Pk', 'Pakistan'), ('O', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Administratore'), ('Data Entry', 'Data Entry')], max_length=11, null=True),
        ),
    ]
