# Generated by Django 4.1.2 on 2023-02-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_team_member_address_alter_team_member_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='country',
            field=models.CharField(blank=True, choices=[('pakistan', 'Pakistan'), ('O', 'Other')], max_length=9, null=True),
        ),
    ]
