# Generated by Django 4.1.2 on 2023-02-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_alter_team_member_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Administratore'), ('Data_Entry', 'Data_Entry')], max_length=11, null=True),
        ),
    ]
