# Generated by Django 4.1.2 on 2023-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_appiontment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontment',
            name='date',
            field=models.DateField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='appiontment',
            name='time',
            field=models.TimeField(blank=True, max_length=15, null=True),
        ),
    ]
