# Generated by Django 4.1.2 on 2023-02-26 17:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_alter_appiontment_date_alter_appiontment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontment',
            name='date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2023, 2, 26))]),
        ),
        migrations.AlterField(
            model_name='appiontment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
