# Generated by Django 4.1.2 on 2023-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_alter_appiontment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontment',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
