# Generated by Django 4.1.2 on 2023-02-26 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_alter_appiontment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appiontment',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
