# Generated by Django 4.1.2 on 2023-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0021_alter_appiontment_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
                ('discription', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='case_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('discription', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
