# Generated by Django 4.1.2 on 2023-02-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0023_court_court_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court_type',
            old_name='court_name',
            new_name='court_type',
        ),
    ]
