# Generated by Django 4.1.2 on 2023-02-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_rename_court_name_court_type_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case_status',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='case_type',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='court_type',
            name='detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
