# Generated by Django 4.1.2 on 2023-02-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_alter_case_status_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court_type',
            old_name='court_type',
            new_name='court_type_name',
        ),
    ]
