# Generated by Django 4.1.2 on 2023-02-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_rename_court_type_court_type_court_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
