# Generated by Django 4.1.2 on 2023-02-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='judge_name',
        ),
        migrations.AddField(
            model_name='judge',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
