# Generated by Django 4.1.2 on 2023-02-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0028_remove_judge_judge_name_judge_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='service_name',
            new_name='judge_name',
        ),
        migrations.RemoveField(
            model_name='judge',
            name='amount',
        ),
    ]
