# Generated by Django 4.1.2 on 2023-02-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0030_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.IntegerField(blank=True, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('act', models.CharField(blank=True, max_length=100, null=True)),
                ('filling_no', models.IntegerField(blank=True, null=True)),
                ('filling_date', models.CharField(blank=True, max_length=20, null=True)),
                ('registeration_no', models.IntegerField(blank=True, null=True)),
                ('registeration_data', models.CharField(blank=True, max_length=20, null=True)),
                ('hiring_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cnr_no', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('police_station_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fir_no', models.IntegerField(blank=True, null=True)),
                ('fir_date', models.CharField(blank=True, max_length=20)),
                ('court_no', models.IntegerField(blank=True, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=200, null=True)),
                ('adovcate_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.team_member')),
                ('case_status_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.case_status')),
                ('case_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.case_type')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.client_detail')),
                ('court_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.court')),
                ('court_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.court_type')),
                ('judge_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='case.judge')),
            ],
        ),
    ]
