# Generated by Django 4.1.2 on 2023-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0032_case_detail_next_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_detail',
            name='city',
            field=models.CharField(choices=[('Peshawar', 'Peshawar'), ('Lahore', 'Lahore'), ('Islamabad', 'islamabad')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='client_detail',
            name='country',
            field=models.CharField(choices=[('pakistan', 'Pakistan'), ('Other', 'Other')], default='', max_length=9),
        ),
    ]
