# Generated by Django 4.1.2 on 2023-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0033_alter_client_detail_city_alter_client_detail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_detail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
    ]
