# Generated by Django 4.1.2 on 2023-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0035_alter_client_detail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_detail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=7),
        ),
    ]
