# Generated by Django 4.1.2 on 2023-02-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0037_alter_client_detail_city_alter_client_detail_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_detail',
            old_name='filling_date',
            new_name='filing_date',
        ),
        migrations.RenameField(
            model_name='case_detail',
            old_name='filling_no',
            new_name='filing_no',
        ),
        migrations.RenameField(
            model_name='case_detail',
            old_name='registeration_data',
            new_name='registeration_date',
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='adovcate_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='case_status_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='case_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='court_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='court_type_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case_detail',
            name='judge_type_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
