# Generated by Django 4.1.2 on 2023-02-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0038_rename_filling_date_case_detail_filing_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_detail',
            old_name='registeration_date',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='case_detail',
            old_name='registeration_no',
            new_name='reg_no',
        ),
    ]
