# Generated by Django 4.1.2 on 2023-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0039_rename_registeration_date_case_detail_reg_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ivioce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invioce_date', models.CharField(blank=True, max_length=100, null=True)),
                ('services_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invioce_no', models.IntegerField(blank=True, null=True)),
                ('services_description', models.CharField(blank=True, max_length=100, null=True)),
                ('taxes_name', models.IntegerField(blank=True, null=True)),
                ('taxes_description', models.CharField(blank=True, max_length=20, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
