# Generated by Django 4.1.2 on 2023-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0040_ivioce'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ivioce',
            new_name='ivioces',
        ),
    ]
