# Generated by Django 4.1.2 on 2023-02-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0041_rename_ivioce_ivioces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ivioces',
            new_name='invioces',
        ),
    ]
