# Generated by Django 4.1.2 on 2023-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0042_rename_ivioces_invioces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invioces',
            name='taxes_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
