# Generated by Django 4.1.2 on 2023-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0043_alter_invioces_taxes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invioce_no', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
