# Generated by Django 4.1.2 on 2023-02-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0049_admin_user_remove_teacher_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
