# Generated by Django 4.1.2 on 2023-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0050_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invioces',
            name='due',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
