# Generated by Django 4.1.2 on 2023-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0051_invioces_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='invioces',
            name='pay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
